In [1]:
import spacy
import pandas as pd
pd.set_option('display.max_colwidth',None)

# Version 1 with Keywords

### Load the pretrained model

In [2]:
nlp = spacy.load('spacy_trained_model_v1')
nlp_sm = spacy.load('en_core_web_sm')
nlp_md = spacy.load('en_core_web_md')

In [3]:
df = pd.read_csv('Generated_English_Queries_Test_Set_v2.csv',keep_default_na=False)
df.head(2)

,English_Queries,Task,Category,Sub_Category,Customer
0,get Revenue for Sub_category Shelf Stable in month Mar?,Revenue,NA,Shelf Stable,NA
1,fetch Top Line for Sub_category Juice in week Wk25 to Wk38?,Top Line,NA,Juice,NA

In [4]:
entities = []
c = 1
for index,row in df.iterrows():
    values = ''
    doc = nlp(row['English_Queries'])
     
    for ent in doc.ents:
        values += ent.text + ':' + ent.label_ +' || '
    entities.append(values)
df['Entities'] = entities

In [5]:
df.head(20)

,English_Queries,Task,Category,Sub_Category,Customer,Entities
0,get Revenue for Sub_category Shelf Stable in month Mar?,Revenue,NA,Shelf Stable,NA,Revenue:Task || Shelf Stable:Sub_Category ||
1,fetch Top Line for Sub_category Juice in week Wk25 to Wk38?,Top Line,NA,Juice,NA,Top Line:Task || Juice:Sub_Category ||
2,display Top Line for the Customer Target in year 2019?,Top Line,NA,NA,Target,Top Line:Task || Target:Customer ||
3,fetch Top Line for category Candy in quarter Q1 to Q4?,Top Line,Candy,NA,NA,Top Line:Task || Candy:Category ||
4,generate Max Shipment for the Customer Albertsons/Safeway in quarter Q1?,Max Shipment,NA,NA,Albertsons/Safeway,Max Shipment:Task || Albertsons/Safeway:Customer ||
5,get Count for the Customer Dollar General in year 2019?,Count,NA,NA,Dollar General,Count:Task || Dollar General:Customer ||
6,get Top Line for Sub_category Ketchup in year 2019?,Top Line,NA,Ketchup,NA,Top Line:Task || Ketchup:Sub_Category ||
7,fetch Net sales for category Cheese in week Wk24 to Wk44?,Net sales,Cheese,NA,NA,Net sales:Task || Cheese:Category ||
8,generate Revenue for the Customer Costco in month Aug?,Revenue,NA,NA,Costco,Revenue:Task || Costco:Customer ||
9,get Count for Sub_category Juice in quarter Q2 to Q4?,Count,NA,Juice,NA,Count:Task || Juice:Sub_Category ||
10,get Gross Sales for category Candy in quarter Q2?,Gross Sales,Candy,NA,NA,Gross Sales:Task || Candy:Category ||
11,display Top Line for category Breakfast in month Mar to Oct?,Top Line,Breakfast,NA,NA,Top Line:Task || Breakfast:Category ||
12,display Top Line for Sub_category Ketchup in month Sep?,Top Line,NA,Ketchup,NA,Top Line:Task || Ketchup:Sub_Category ||
13,display Net sales for category Candy in quarter Q1 to Q4?,Net sales,Candy,NA,NA,Net sales:Task || Candy:Category ||
14,display Bottom Line for the Customer Ahold in month Apr?,Bottom Line,NA,NA,Ahold,Bottom Line:Task || Ahold:Customer ||
15,display Net sales for category Breakfast in week Wk13 to Wk36?,Net sales,Breakfast,NA,NA,Net sales:Task || Breakfast:Category ||
16,fetch Count for Sub_category Ketchup in quarter Q4?,Count,NA,Ketchup,NA,Count:Task || Ketchup:Sub_Category ||
17,get Top Line for category Cheese in month Jan to Sep?,Top Line,Cheese,NA,NA,Top Line:Task || Cheese:Category ||
18,get Top Line for the Customer Amazon in quarter Q1?,Top Line,NA,NA,Amazon,Top Line:Task || Amazon:Customer ||
19,display Count for category Candy in week Wk15 to Wk41?,Count,Candy,NA,NA,Count:Task || Candy:Category ||

In [6]:
## Creating Spacy objects of English Queries:
nlp_text_df_sm = {}
nlp_text_df_md = {}
for i in range(len(df)):
    nlp_text_df_sm[i] = nlp_sm(df['English_Queries'][i])
    nlp_text_df_md[i] = nlp_md(df['English_Queries'][i])

In [7]:
len(nlp_text_df_sm), len(nlp_text_df_md)

(100, 100)

In [8]:
## Time Information extraction:
# Let's exract information from the above sentence
time_dict_sm = {}
time_dict_md = {}

for i in range(len(nlp_text_df_md)):
    temp_time_sm = []
    temp_time_md = []
    
    for token in nlp_text_df_sm[i]:
        if token.ent_type_ == 'DATE':
            temp_time_sm.append(token)

    for token in nlp_text_df_md[i]:
                 
        if token.ent_type_ == 'DATE':
            temp_time_md.append(token)
    
    time_dict_sm[i] = temp_time_sm
    time_dict_md[i] = temp_time_md

In [9]:
df2 = df[['English_Queries','Entities']]
df2['time_info_sm'] = time_dict_sm.values()
df2['time_info_md'] = time_dict_md.values()

<ipython-input-9-42cde77e910c>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['time_info_sm'] = time_dict_sm.values()
<ipython-input-9-42cde77e910c>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['time_info_md'] = time_dict_md.values()

In [10]:
df2.head(20)

,English_Queries,Entities,time_info_sm,time_info_md
0,get Revenue for Sub_category Shelf Stable in month Mar?,Revenue:Task || Shelf Stable:Sub_Category ||,"[month, Mar]","[month, Mar]"
1,fetch Top Line for Sub_category Juice in week Wk25 to Wk38?,Top Line:Task || Juice:Sub_Category ||,[week],[week]
2,display Top Line for the Customer Target in year 2019?,Top Line:Task || Target:Customer ||,"[year, 2019]","[year, 2019]"
3,fetch Top Line for category Candy in quarter Q1 to Q4?,Top Line:Task || Candy:Category ||,"[quarter, Q1]","[quarter, Q1]"
4,generate Max Shipment for the Customer Albertsons/Safeway in quarter Q1?,Max Shipment:Task || Albertsons/Safeway:Customer ||,"[quarter, Q1]","[quarter, Q1]"
5,get Count for the Customer Dollar General in year 2019?,Count:Task || Dollar General:Customer ||,"[year, 2019]","[year, 2019]"
6,get Top Line for Sub_category Ketchup in year 2019?,Top Line:Task || Ketchup:Sub_Category ||,"[year, 2019]","[year, 2019]"
7,fetch Net sales for category Cheese in week Wk24 to Wk44?,Net sales:Task || Cheese:Category ||,[week],[week]
8,generate Revenue for the Customer Costco in month Aug?,Revenue:Task || Costco:Customer ||,"[month, Aug]","[month, Aug]"
9,get Count for Sub_category Juice in quarter Q2 to Q4?,Count:Task || Juice:Sub_Category ||,[],"[quarter, Q2]"
10,get Gross Sales for category Candy in quarter Q2?,Gross Sales:Task || Candy:Category ||,[],"[quarter, Q2]"
11,display Top Line for category Breakfast in month Mar to Oct?,Top Line:Task || Breakfast:Category ||,"[month, Mar, to, Oct]","[month, Mar, to, Oct]"
12,display Top Line for Sub_category Ketchup in month Sep?,Top Line:Task || Ketchup:Sub_Category ||,[],"[month, Sep]"
13,display Net sales for category Candy in quarter Q1 to Q4?,Net sales:Task || Candy:Category ||,[],"[quarter, Q1]"
14,display Bottom Line for the Customer Ahold in month Apr?,Bottom Line:Task || Ahold:Customer ||,[month],"[month, Apr]"
15,display Net sales for category Breakfast in week Wk13 to Wk36?,Net sales:Task || Breakfast:Category ||,[week],[week]
16,fetch Count for Sub_category Ketchup in quarter Q4?,Count:Task || Ketchup:Sub_Category ||,"[quarter, Q4]",[quarter]
17,get Top Line for category Cheese in month Jan to Sep?,Top Line:Task || Cheese:Category ||,"[month, Jan]","[month, Jan, to, Sep]"
18,get Top Line for the Customer Amazon in quarter Q1?,Top Line:Task || Amazon:Customer ||,"[quarter, Q1]","[quarter, Q1]"
19,display Count for category Candy in week Wk15 to Wk41?,Count:Task || Candy:Category ||,[week],[week]

In [11]:
df2.to_csv('English_Queries_with_Info_extracted.csv',index=False)

# Version 2 without Keywords

### Load the pretrained model

In [12]:
nlp_v2 = spacy.load('spacy_trained_model_v2')

In [13]:
df_v2 = pd.read_csv('Generated_English_Queries_v3_without_keyword_Test_Set.csv',keep_default_na=False)
df_v2.head(2)

,English_Queries,Task,Category,Sub_Category,Customer
0,generate Max Shipment Candy in quarter Q2?,Max Shipment,Candy,NA,NA
1,generate Top Line Sauces in quarter Q1 to Q4?,Top Line,Sauces,NA,NA

In [14]:
entities = []
c = 1
for index,row in df_v2.iterrows():
    values = ''
    doc = nlp_v2(row['English_Queries'])
     
    for ent in doc.ents:
        values += ent.text + ':' + ent.label_ +' || '
    entities.append(values)
df_v2['Entities'] = entities

In [15]:
df.head(20)

,English_Queries,Task,Category,Sub_Category,Customer,Entities
0,get Revenue for Sub_category Shelf Stable in month Mar?,Revenue,NA,Shelf Stable,NA,Revenue:Task || Shelf Stable:Sub_Category ||
1,fetch Top Line for Sub_category Juice in week Wk25 to Wk38?,Top Line,NA,Juice,NA,Top Line:Task || Juice:Sub_Category ||
2,display Top Line for the Customer Target in year 2019?,Top Line,NA,NA,Target,Top Line:Task || Target:Customer ||
3,fetch Top Line for category Candy in quarter Q1 to Q4?,Top Line,Candy,NA,NA,Top Line:Task || Candy:Category ||
4,generate Max Shipment for the Customer Albertsons/Safeway in quarter Q1?,Max Shipment,NA,NA,Albertsons/Safeway,Max Shipment:Task || Albertsons/Safeway:Customer ||
5,get Count for the Customer Dollar General in year 2019?,Count,NA,NA,Dollar General,Count:Task || Dollar General:Customer ||
6,get Top Line for Sub_category Ketchup in year 2019?,Top Line,NA,Ketchup,NA,Top Line:Task || Ketchup:Sub_Category ||
7,fetch Net sales for category Cheese in week Wk24 to Wk44?,Net sales,Cheese,NA,NA,Net sales:Task || Cheese:Category ||
8,generate Revenue for the Customer Costco in month Aug?,Revenue,NA,NA,Costco,Revenue:Task || Costco:Customer ||
9,get Count for Sub_category Juice in quarter Q2 to Q4?,Count,NA,Juice,NA,Count:Task || Juice:Sub_Category ||
10,get Gross Sales for category Candy in quarter Q2?,Gross Sales,Candy,NA,NA,Gross Sales:Task || Candy:Category ||
11,display Top Line for category Breakfast in month Mar to Oct?,Top Line,Breakfast,NA,NA,Top Line:Task || Breakfast:Category ||
12,display Top Line for Sub_category Ketchup in month Sep?,Top Line,NA,Ketchup,NA,Top Line:Task || Ketchup:Sub_Category ||
13,display Net sales for category Candy in quarter Q1 to Q4?,Net sales,Candy,NA,NA,Net sales:Task || Candy:Category ||
14,display Bottom Line for the Customer Ahold in month Apr?,Bottom Line,NA,NA,Ahold,Bottom Line:Task || Ahold:Customer ||
15,display Net sales for category Breakfast in week Wk13 to Wk36?,Net sales,Breakfast,NA,NA,Net sales:Task || Breakfast:Category ||
16,fetch Count for Sub_category Ketchup in quarter Q4?,Count,NA,Ketchup,NA,Count:Task || Ketchup:Sub_Category ||
17,get Top Line for category Cheese in month Jan to Sep?,Top Line,Cheese,NA,NA,Top Line:Task || Cheese:Category ||
18,get Top Line for the Customer Amazon in quarter Q1?,Top Line,NA,NA,Amazon,Top Line:Task || Amazon:Customer ||
19,display Count for category Candy in week Wk15 to Wk41?,Count,Candy,NA,NA,Count:Task || Candy:Category ||

In [16]:
## Creating Spacy objects of English Queries:
nlp_text_df_sm_v2 = {}
nlp_text_df_md_v2 = {}
for i in range(len(df_v2)):
    nlp_text_df_sm_v2[i] = nlp_sm(df_v2['English_Queries'][i])
    nlp_text_df_md_v2[i] = nlp_md(df_v2['English_Queries'][i])

In [17]:
## Time Information extraction:
time_dict_sm_v2 = {}
time_dict_md_v2 = {}

for i in range(len(nlp_text_df_md)):
    temp_time_sm_v2 = []
    temp_time_md_v2 = []
    
    for token in nlp_text_df_sm_v2[i]:
        if token.ent_type_ == 'DATE':
            temp_time_sm_v2.append(token)

    for token in nlp_text_df_md_v2[i]:
                 
        if token.ent_type_ == 'DATE':
            temp_time_md_v2.append(token)
    
    time_dict_sm_v2[i] = temp_time_sm_v2
    time_dict_md_v2[i] = temp_time_md_v2

In [18]:
df2_v2 = df_v2[['English_Queries','Entities']]
df2_v2['time_info_sm'] = time_dict_sm_v2.values()
df2_v2['time_info_md'] = time_dict_md_v2.values()

<ipython-input-18-e898aa831461>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2_v2['time_info_sm'] = time_dict_sm_v2.values()
<ipython-input-18-e898aa831461>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2_v2['time_info_md'] = time_dict_md_v2.values()

In [19]:
df2_v2.head(20)

,English_Queries,Entities,time_info_sm,time_info_md
0,generate Max Shipment Candy in quarter Q2?,Max Shipment:Task || Candy:Category ||,"[quarter, Q2]","[quarter, Q2]"
1,generate Top Line Sauces in quarter Q1 to Q4?,Top Line:Task || Sauces:Category ||,[],"[quarter, Q1]"
2,display Net sales Tea in month Nov?,Net sales:Task || Tea:Sub_Category ||,"[month, Nov]","[month, Nov]"
3,get Top Line Ketchup in year 2019?,Top Line:Task || Ketchup:Sub_Category ||,"[year, 2019]","[year, 2019]"
4,get Revenue Hot Dogs in month Aug?,Revenue:Task || Hot Dogs:Sub_Category ||,"[month, Aug]","[month, Aug]"
5,fetch Bottom Line Candy in month Jun to Nov?,Bottom Line:Task || Candy:Category ||,[month],"[month, Jun, to, Nov]"
6,fetch Revenue Albertsons/Safeway in month Oct?,Revenue:Task || Albertsons/Safeway:Customer ||,"[month, Oct]","[month, Oct]"
7,fetch Top Line UNIFI in year 2019?,Top Line:Task || UNIFI:Customer ||,"[year, 2019]","[year, 2019]"
8,fetch Revenue Meats in year 2019?,Revenue:Task || Meats:Category ||,"[year, 2019]","[year, 2019]"
9,fetch Revenue Cheese in week Wk16 to Wk43?,Revenue:Task || Cheese:Category ||,[week],[]
10,generate Gross Sales Meats in year 2019?,Gross Sales:Task || Meats:Category ||,"[year, 2019]","[year, 2019]"
11,display Bottom Line Walmart in week Wk14 to Wk28?,Bottom Line:Task || Walmart:Customer ||,"[week, Wk14]",[week]
12,get Max Shipment Ahold in year 2019?,Max Shipment:Task || Ahold:Customer ||,"[year, 2019]","[year, 2019]"
13,generate Net sales Cheese in year 2019?,Net sales:Task || Cheese:Category ||,"[year, 2019]","[year, 2019]"
14,display Revenue Tea in week Wk43?,Revenue:Task || Tea:Sub_Category ||,"[week, Wk43]",[week]
15,get Count Walmart in month Feb to Sep?,Count:Task || Walmart:Customer ||,[month],"[month, Feb, to, Sep]"
16,display Top Line Candy in year 2019?,Top Line:Task || Candy:Category ||,"[year, 2019]","[year, 2019]"
17,generate Bottom Line Hard in year 2019?,Bottom Line:Task || Hard:Sub_Category ||,"[year, 2019]","[year, 2019]"
18,fetch Max Shipment Cheese in year 2019?,Max Shipment:Task || Cheese:Category ||,"[year, 2019]","[year, 2019]"
19,fetch Net sales Dollar General in month May to Dec?,Net sales:Task || Dollar General:Customer ||,"[month, May]","[month, May, to, Dec]"

In [22]:
df2_v2.to_csv('English_Queries_Without_Keywords_with_Info_extracted.csv',index=False)

## Test

In [ ]:
#!python -m spacy download en_core_web_md

In [ ]:
# ## This cell is for test purpose only
text = 'get Count for Sub_category Juice in quarter Q2 to Q4?'
nlp_text = nlp_md(text)
for token in nlp_text:
    print(token.text, '-->', token.pos_, '-->', token.ent_iob_,'-->',token.ent_type_)

In [ ]:
text = "get Gross Sales for category Candy in quarter Q2?"
nlp_text = nlp_md(text)
for token in nlp_text:
    print(token.text, '-->', token.pos_, '-->', token.ent_iob_,'-->',token.ent_type_)

In [ ]:
text = "get Gross Sales for category Candy in quarter Q2?"
nlp_text = nlp_standard(text)
for token in nlp_text:
    print(token.text, '-->', token.pos_, '-->', token.ent_iob_,'-->',token.ent_type_)