In [1]:
import spacy
import pandas as pd

# Version 1 with Keywords

### Load the pretrained model

In [2]:
nlp = spacy.load('spacy_trained_model_v1')

In [3]:
df = pd.read_csv('Generated_English_Queries_Test_Set_v2.csv',keep_default_na=False)
df.head(2)

,English_Queries,Task,Category,Sub_Category,Customer
0,get Revenue for Sub_category Shelf Stable in m...,Revenue,NA,Shelf Stable,NA
1,fetch Top Line for Sub_category Juice in week ...,Top Line,NA,Juice,NA

In [4]:
entities = []
c = 1
for index,row in df.iterrows():
    values = ''
    doc = nlp(row['English_Queries'])
     
    for ent in doc.ents:
        values += ent.text + ':' + ent.label_ +' || '
    entities.append(values)
df['Entities'] = entities

In [5]:
df.head(20)

,English_Queries,Task,Category,Sub_Category,Customer,Entities
0,get Revenue for Sub_category Shelf Stable in m...,Revenue,NA,Shelf Stable,NA,Revenue:Task || Shelf Stable:Sub_Category ||
1,fetch Top Line for Sub_category Juice in week ...,Top Line,NA,Juice,NA,Top Line:Task || Juice:Sub_Category ||
2,display Top Line for the Customer Target in ye...,Top Line,NA,NA,Target,Top Line:Task || Target:Customer ||
3,fetch Top Line for category Candy in quarter Q...,Top Line,Candy,NA,NA,Top Line:Task || Candy:Category ||
4,generate Max Shipment for the Customer Alberts...,Max Shipment,NA,NA,Albertsons/Safeway,Max Shipment:Task || Albertsons/Safeway:Custom...
5,get Count for the Customer Dollar General in y...,Count,NA,NA,Dollar General,Count:Task || Dollar General:Customer ||
6,get Top Line for Sub_category Ketchup in year ...,Top Line,NA,Ketchup,NA,Top Line:Task || Ketchup:Sub_Category ||
7,fetch Net sales for category Cheese in week Wk...,Net sales,Cheese,NA,NA,Net sales:Task || Cheese:Category ||
8,generate Revenue for the Customer Costco in mo...,Revenue,NA,NA,Costco,Revenue:Task || Costco:Customer ||
9,get Count for Sub_category Juice in quarter Q2...,Count,NA,Juice,NA,Count:Task || Juice:Sub_Category ||
10,get Gross Sales for category Candy in quarter Q2?,Gross Sales,Candy,NA,NA,Gross Sales:Task || Candy:Category ||
11,display Top Line for category Breakfast in mon...,Top Line,Breakfast,NA,NA,Top Line:Task || Breakfast:Category ||
12,display Top Line for Sub_category Ketchup in m...,Top Line,NA,Ketchup,NA,Top Line:Task || Ketchup:Sub_Category ||
13,display Net sales for category Candy in quarte...,Net sales,Candy,NA,NA,Net sales:Task || Candy:Category ||
14,display Bottom Line for the Customer Ahold in ...,Bottom Line,NA,NA,Ahold,Bottom Line:Task || Ahold:Customer ||
15,display Net sales for category Breakfast in we...,Net sales,Breakfast,NA,NA,Net sales:Task || Breakfast:Category ||
16,fetch Count for Sub_category Ketchup in quarte...,Count,NA,Ketchup,NA,Count:Task || Ketchup:Sub_Category ||
17,get Top Line for category Cheese in month Jan ...,Top Line,Cheese,NA,NA,Top Line:Task || Cheese:Category ||
18,get Top Line for the Customer Amazon in quarte...,Top Line,NA,NA,Amazon,Top Line:Task || Amazon:Customer ||
19,display Count for category Candy in week Wk15 ...,Count,Candy,NA,NA,Count:Task || Candy:Category ||

# Version 2 without Keywords

### Load the pretrained model

In [6]:
nlp = spacy.load('spacy_trained_model_v2')

In [7]:
df = pd.read_csv('Generated_English_Queries_v3_without_keyword_Test_Set.csv',keep_default_na=False)
df.head(2)

,English_Queries,Task,Category,Sub_Category,Customer
0,generate Max Shipment Candy in quarter Q2?,Max Shipment,Candy,NA,NA
1,generate Top Line Sauces in quarter Q1 to Q4?,Top Line,Sauces,NA,NA

In [8]:
entities = []
c = 1
for index,row in df.iterrows():
    values = ''
    doc = nlp(row['English_Queries'])
     
    for ent in doc.ents:
        values += ent.text + ':' + ent.label_ +' || '
    entities.append(values)
df['Entities'] = entities

In [9]:
df.head(20)

,English_Queries,Task,Category,Sub_Category,Customer,Entities
0,generate Max Shipment Candy in quarter Q2?,Max Shipment,Candy,NA,NA,Max Shipment:Task || Candy:Category ||
1,generate Top Line Sauces in quarter Q1 to Q4?,Top Line,Sauces,NA,NA,Top Line:Task || Sauces:Category ||
2,display Net sales Tea in month Nov?,Net sales,NA,Tea,NA,Net sales:Task || Tea:Sub_Category ||
3,get Top Line Ketchup in year 2019?,Top Line,NA,Ketchup,NA,Top Line:Task || Ketchup:Sub_Category ||
4,get Revenue Hot Dogs in month Aug?,Revenue,NA,Hot Dogs,NA,Revenue:Task || Hot Dogs:Sub_Category ||
5,fetch Bottom Line Candy in month Jun to Nov?,Bottom Line,Candy,NA,NA,Bottom Line:Task || Candy:Category ||
6,fetch Revenue Albertsons/Safeway in month Oct?,Revenue,NA,NA,Albertsons/Safeway,Revenue:Task || Albertsons/Safeway:Customer ||
7,fetch Top Line UNIFI in year 2019?,Top Line,NA,NA,UNIFI,Top Line:Task || UNIFI:Customer ||
8,fetch Revenue Meats in year 2019?,Revenue,Meats,NA,NA,Revenue:Task || Meats:Category ||
9,fetch Revenue Cheese in week Wk16 to Wk43?,Revenue,Cheese,NA,NA,Revenue:Task || Cheese:Category ||
10,generate Gross Sales Meats in year 2019?,Gross Sales,Meats,NA,NA,Gross Sales:Task || Meats:Category ||
11,display Bottom Line Walmart in week Wk14 to W...,Bottom Line,NA,NA,Walmart,Bottom Line:Task || Walmart:Customer ||
12,get Max Shipment Ahold in year 2019?,Max Shipment,NA,NA,Ahold,Max Shipment:Task || Ahold:Customer ||
13,generate Net sales Cheese in year 2019?,Net sales,Cheese,NA,NA,Net sales:Task || Cheese:Category ||
14,display Revenue Tea in week Wk43?,Revenue,NA,Tea,NA,Revenue:Task || Tea:Sub_Category ||
15,get Count Walmart in month Feb to Sep?,Count,NA,NA,Walmart,Count:Task || Walmart:Customer ||
16,display Top Line Candy in year 2019?,Top Line,Candy,NA,NA,Top Line:Task || Candy:Category ||
17,generate Bottom Line Hard in year 2019?,Bottom Line,NA,Hard,NA,Bottom Line:Task || Hard:Sub_Category ||
18,fetch Max Shipment Cheese in year 2019?,Max Shipment,Cheese,NA,NA,Max Shipment:Task || Cheese:Category ||
19,fetch Net sales Dollar General in month May t...,Net sales,NA,NA,Dollar General,Net sales:Task || Dollar General:Customer ||